logsources:
  windows:
    product: windows
    index: logstash-win-*
  windows-application:
    product: windows
    service: application
    conditions:
      EventLog: Application
  windows-security:
    product: windows
    service: security
    conditions:
      EventLog: Security
  windows-sysmon:
    product: windows
    service: sysmon
    conditions:
      EventLog: Microsoft-Windows-Sysmon
  windows-dns-server:
    product: windows
    service: dns-server
    conditions:
      EventLog: 'DNS Server'
  windows-driver-framework:
    product: windows
    service: driver-framework
    conditions:
      source: 'Microsoft-Windows-DriverFrameworks-UserMode/Operational'
fieldmappings:
  EventID: event_id
  EngineVersion: process.EngineVersion
  HostVersion: process.HostVersion
defaultindex: logstash-*
